mode: balance # 模式 balance(均衡模式)、parallel(平行模式)
containers: # 容器，可配置多个
  - address: http://192.168.31.233:5700
    username: admin
    password: admin
    cid: admin # 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    secret: admin # 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    weigth:  # 权重 balance模式下权重越高分得的ck越多，默认1 
    mode: parallel # 单独对容器进行模式设置
    limit: 9999 # 限制容器ck数目
AtTime:  # 填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp:  # 填写true或者false 默认false 是否往容器添加助力码
IsOldV4:  # 填写true或者false 默认false 是否新版或者旧版V4
Wskey:  # 填空默认禁用wskey转换 需要的填true
IsAddFriend:  #填写true或者false  false
Lim:  # 填写1-N 代表限制次数
Tyt:  # 填写1-N 代表推一推需要的互助值，默认为8
Later:  # 延时防止黑IP自己设置 默认60 不怕黑的改为1即可 单位是秒
ApiToken:  # 短信接入token参数
GameOpen:  # 自定义是否开启游戏比如搏一把功能。
Note:  # 填写pin或者note  填写pin青龙的备注会是pin填写note就是xdd的备注同步到青龙
Jdcurl: http://127.0.0.1:5701
theme: ./theme/admin.html # 自定义主题，支持本地、网络路径
static: ./static # 静态文件 便于自定义二维码页面时，引入css、js等文件
master:  #管理员账户pin，有多个用'&'拼接（访问ip:8080/admin使用）可以自定义密码如  admin 后面不能有注释，配置后删除
database:  #数据库位置，默认./.jdc.db 
qywx_key:  #企业微信推送key
daily_push:  #定时任务
resident:  #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。
user_agent:
telegram_bot_token:
telegram_user_id:
TGURL:  #填写TG代理地址参考https://www.kejiwanjia.com/server/5221.html#3worker
qquid:  #接收通知的qq号
qqgid:  #监听的群
qqgids:   #监听多个QQ群 格式:12345678&87654321&1827362513
qqvid:  #VIP验证
qbot_public_mode:  #qq机器人群聊模式，默认私聊模式
default_priority:  #新用户默认优先级（默认就行，默认是1）
qbot_config_file: ./conf/qbot.conf
no_ghproxy:  #更新资源是否不使用代理 默认false
daily_asset_push_cron:  #日常资产推送时间
repos:
  - git: https://github.com/shufflewzc/faker2.git
